### ISSUE TITLE
Error when the "Send reject message to" is selected

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/filter-component#5]
When the `(Optional) Send reject message to` parameter is selected an error is reported.

## To Replicate

1. Build an integration flow in any workspace where you have another active flow starting with WebHook.
2. The second step is the Filter component.
3. Input any expression for the `Filter condition`, need to evaluate `true/false`. Use JavaScript.
4. Select the drop-down menu `(Optional) Send reject message to` to select any flow.

ER: You get the list of Flow IDs

AR: The following Error is reported:

```
403 - {"errors":[{"detail":"Workspace is not found","status":403,"code":403,"title":"Unauthorized","meta":{}}]}
```

The log has more on this error:
```
Starting your Docker container ...
[INFO  tini (1)] Spawned child process '/run.sh' with pid '7'
Starting application in apprunner...
Starting slug download ...
Successfully downloaded and extracted slug file
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
at Request.plumbing.callback (/home/apprunner/node_modules/request-promise-core/lib/plumbing.js:104:33)
at Request.emit (events.js:194:7)
at emitNone (events.js:91:20)
at endReadableNT (_stream_readable.js:975:12)
at process._tickCallback (internal/process/next_tick.js:104:9)
highWaterMark: 16384,
buffer: [Object],
defaultEncoding: 'utf8',
_newSessionPending: false,
_controlReleased: true,
_tlsOptions: [Object],
_eventsCount: 9,
_sockname: null,
_pendingEncoding: '',
_idlePrev: null,
_idleTimeout: -1 },
_secureEstablished: true,
_securePending: false,
authorized: true,
_handle: null,
readable: false,
destroyed: true,
_pendingEncoding: '',
server: undefined,
_requestCert: true,
_idlePrev: null,
httpVersionMinor: 1,
complete: true,
_maxListeners: undefined,
read: [Function],
_consuming: true,
_dumped: false,
output: [],
outputEncodings: [],
outputCallbacks: [],
writable: true,
upgrading: false,
_removedHeader: {},
finished: true,
socket: [Object],
connection: [Object],
_header: 'GET /v2/flows/ HTTP/1.1\r\nhost: api.elastic.io\r\nauthorization: Basic dGlncmFuQGVsYXN0aWMuaW86NTJjNGFlYWUtOTYyYS00ZjExLWI5NDMtMzU4MWI0MDcwOGY5\r\naccept: application/json\r\nConnection: close\r\n\r\n',
path: '/v2/flows/',
parser: null,
maxHeadersCount: null },
Request {
readable: true,
_qs: [Object],
_oauth: [Object],
_rp_resolve: [Function],
dests: [],
setHost: true,
pool: {},
host: 'api.elastic.io',
agent: [Object],
[INFO  tini (1)] Main child exited normally (with status '0')
at emitOne (events.js:96:13)
at Request.emit (events.js:191:7)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
statusCode: 403,
error: { errors: [ [Object] ] },
transform: undefined,
resolveWithFullResponse: false,
IncomingMessage {
ReadableState {
pipesCount: 0,
flowing: true,
endEmitted: true,
emittedReadable: false,
needReadable: false,
readableListening: false,
ranOut: false,
_events:
{ end: [Object],
_securePending: false,
_SNICallback: null,
_eventsCount: 9,
_sockname: null,
_pendingEncoding: '',
_idlePrev: null,
_idleTimeout: -1 },
_secureEstablished: true,
_securePending: false,
authorized: true,
_handle: null,
readable: false,
destroyed: true,
_pendingEncoding: '',
server: undefined,
_requestCert: true,
_idlePrev: null,
httpVersionMinor: 1,
complete: true,
_maxListeners: undefined,
read: [Function],
_consuming: true,
_dumped: false,
output: [],
outputEncodings: [],
outputCallbacks: [],
writable: true,
upgrading: false,
_removedHeader: {},
finished: true,
socket: [Object],
connection: [Object],
_header: 'GET /v2/flows/ HTTP/1.1\r\nhost: api.elastic.io\r\nauthorization: Basic dGlncmFuQGVsYXN0aWMuaW86NTJjNGFlYWUtOTYyYS00ZjExLWI5NDMtMzU4MWI0MDcwOGY5\r\naccept: application/json\r\nConnection: close\r\n\r\n',
path: '/v2/flows/',
parser: null,
maxHeadersCount: null },
Request {
readable: true,
_qs: [Object],
_oauth: [Object],
_events: [Object],
_parent: null,
_host: 'api.elastic.io',
_readableState: [Object],
_maxListeners: undefined,
_writableState: [Object],
writable: false,
_pendingData: null,
server: undefined,
_server: null,
parser: null,
_httpMessage: [Object],
authorized: true,
npnProtocol: false,
encrypted: true,
_events: [Object],
connecting: false,
_maxListeners: undefined,
_sockname: null,
_httpMessage: [Object],
read: [Function],
_consuming: true,
connecting: false,
httpVersion: '1.1',
readable: false,
_readableState: [Object],
_writableState: [Object],
allowHalfOpen: false,
_server: null,
ssl: null,
_requestCert: true,
_idleNext: null,
_idlePrev: null,
domain: null,
_eventsCount: 5,
_last: true,
chunkedEncoding: false,
_hasBody: true,
_trailer: '',
_onPendingData: null,
method: 'GET',
timeout: undefined,
```

**Comment by jhorbulyk** [comment]
This issue is related to functionality that is now deprecated.  Closing...
